### ISSUE TITLE
Not apearing on Contributors page

### ISSUE THREAD

**Issue by soltys** [NetDevelopersPoland/NetDevPLWebsite#51]
Two accepted pull requests and still no princesce on page. https://github.com/NetDevelopersPoland/NetDevPLWebsite/pull/45 https://github.com/NetDevelopersPoland/NetDevPLWebsite/pull/44. Why?

**Comment by pawelklimczyk** [comment]
I've merged several commits today, but your commits are still not counted. There was something wrong because your and @suvroc changes were not merged previously... strange.

The reason maybe in this in your case (I saw @suvroc appears on contributors page and here: https://api.github.com/repos/NetDevelopersPoland/NetDevPLWebsite/contributors)
![image](https://cloud.githubusercontent.com/assets/1084668/19618383/46888ca8-9849-11e6-9cd6-c1f1c47ba5ad.png)

What is your github username?

**Comment by pawelklimczyk** [comment]
It seems that you have commited changes some other way. Here is your commit to CodeWatch. The username is present (soltys)
![image](https://cloud.githubusercontent.com/assets/1084668/19618463/31bbff9c-984b-11e6-84a6-5edc6d729cc4.png)

**Comment by soltys** [comment]
Yeah, it was case of not adding pawel@soltysiak.it as my email in Github profile.

**Comment by pawelklimczyk** [comment]
But please check if you appear on the contributors page next time.... :)
